const farmersdelightblocklist = ["wild_cabbages",
                           "wild_tomatoes",
                           "wild_onions",
                           "wild_carrots",
                           "wild_potatoes",
                           "wild_beetroots",
                           "wild_rice",
                           "brown_mushroom_colony",
                           "red_mushroom_colony"]
const farmersdelightitemlist = ["cabbage",
                          "rice_panicle",
                          "wheat_dough",
                          "ham",
                          "smoked_ham",
                          "apple_pie",
                          "sweet_berry_cheesecake",
                          "chocolate_pie"
                          ]
const vanillaitemlist = ["cake",
                   "clownfish",
                   "cooked_fish",
                   "fish",
                   "cooked_salmon",
                   "salmon",
                   "porkchop",
                   "beef",
                   "chicken"]